# Generated by Django 5.1.1 on 2024-10-06 22:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('animes', '0003_rename_genre_anime_genres'),
        ('user', '0002_userprofile_profile_picture'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='favorites',
            field=models.ManyToManyField(blank=True, related_name='favorited_by', to='animes.anime'),
        ),
    ]
