# Generated by Django 5.1.1 on 2024-09-25 01:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Genres',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('Genre_name', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Animes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_romaji', models.CharField(max_length=255)),
                ('title_english', models.CharField(blank=True, max_length=255)),
                ('plot', models.TextField()),
                ('episodes', models.PositiveIntegerField()),
                ('season', models.CharField(max_length=50)),
                ('anime_type', models.CharField(choices=[('ANIME', 'Anime'), ('MOVIE', 'Movie')], max_length=50)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField(blank=True, null=True)),
                ('studio', models.CharField(blank=True, max_length=100)),
                ('status', models.CharField(choices=[('ONGOING', 'Ongoing'), ('FINISHED', 'Finished')], default='ONGOING', max_length=50)),
                ('genres', models.ManyToManyField(to='animes.genres')),
            ],
        ),
    ]
