# Generated by Django 5.1.1 on 2024-10-06 00:31

import animes.models
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='genre',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('genre_name', models.CharField(max_length=20, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='anime',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title_romaji', models.CharField(max_length=50)),
                ('title_english', models.CharField(blank=True, max_length=50)),
                ('plot', models.TextField()),
                ('episodes', models.PositiveIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1)])),
                ('season', models.CharField(choices=[('WINTER', 'Winter'), ('SPRING', 'Spring'), ('SUMMER', 'Summer'), ('FALL', 'Fall')], max_length=6)),
                ('anime_type', models.CharField(choices=[('ANIME', 'Anime Series'), ('MOVIE', 'Movie'), ('OVA', 'Original Video Animation'), ('ONA', 'Original Net Animation'), ('SPECIAL', 'Special')], max_length=24)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField(blank=True, null=True)),
                ('studio', models.CharField(blank=True, max_length=20)),
                ('cover_image', models.ImageField(default='anime_images/covers/default_cover.jpg', upload_to=animes.models.generate_filename)),
                ('status', models.CharField(choices=[('ONGOING', 'Ongoing'), ('FINISHED', 'Finished')], default='ONGOING', max_length=20)),
                ('genres', models.ManyToManyField(to='animes.genre')),
            ],
        ),
    ]
