# Generated by Django 5.1.1 on 2024-10-06 00:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('animes', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='anime',
            old_name='genres',
            new_name='genre',
        ),
    ]
