# Generated by Django 5.1.1 on 2024-10-05 02:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('animes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='animes',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
