# Generated by Django 5.1.1 on 2024-10-05 03:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('animes', '0002_alter_animes_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='animes',
            name='season',
            field=models.CharField(choices=[('WINTER', 'Winter'), ('SPRING', 'Spring'), ('SUMMER', 'Summer'), ('FALL', 'Fall')], max_length=6),
        ),
    ]
