# Generated by Django 5.1.1 on 2024-10-06 00:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('animes', '0002_rename_genres_anime_genre'),
    ]

    operations = [
        migrations.RenameField(
            model_name='anime',
            old_name='genre',
            new_name='genres',
        ),
    ]
