# Generated by Django 5.1.1 on 2024-10-05 03:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('animes', '0003_alter_animes_season'),
    ]

    operations = [
        migrations.AlterField(
            model_name='animes',
            name='anime_type',
            field=models.CharField(choices=[('ANIME', 'Anime Series'), ('MOVIE', 'Movie'), ('OVA', 'Original Video Animation'), ('ONA', 'Original Net Animation'), ('SPECIAL', 'Special')], max_length=50),
        ),
    ]
