# Generated by Django 5.1.1 on 2024-10-05 04:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('animes', '0004_alter_animes_anime_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='animes',
            name='title_english',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='animes',
            name='title_romaji',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='genres',
            name='Genre_name',
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
