# Generated by Django 5.1.1 on 2024-10-05 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('animes', '0005_alter_animes_title_english_alter_animes_title_romaji_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='animes',
            name='cover_image',
            field=models.ImageField(blank=True, upload_to='anime_images/covers'),
        ),
        migrations.AlterField(
            model_name='animes',
            name='status',
            field=models.CharField(choices=[('ONGOING', 'Ongoing'), ('FINISHED', 'Finished')], default='ONGOING', max_length=20),
        ),
        migrations.AlterField(
            model_name='animes',
            name='studio',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
