# Generated by Django 5.1.1 on 2024-10-05 19:38

import animes.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('animes', '0006_animes_cover_image_alter_animes_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='animes',
            name='cover_image',
            field=models.ImageField(default='anime_images/covers/default_cover.jpg', upload_to=animes.models.generate_filename),
        ),
    ]
